name = "vfxrun-website"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "vfxrun-wishlist"
database_id = "950ceb47-c7b3-4507-858f-6c4674e902bf"
